### ISSUE TITLE
Popup viewer spawns far away from the cursor

### ISSUE THREAD

**Issue by branimir1999** [clippydsdone/clippy-frontend#114]

**Comment by nsm18002** [comment]
2022-12-17 10:00 - 12:00 + 13:00 - 17:00 + 18:00 - 22:00, 10h
- Reworked movement to now use JQuery, looks a lot cleaner and handles better.
- Reworked "spawn position" math of the popup, hopefully it now works universally.
- Resize functionality added.
- Content scaling/zooming implemented.
- Made sidebar container opaque to no longer cause popups to be visible behind it.
- Set a default background color for popups to remove visible gaps between pages causing the document behind to bleed through.
- Default popup window size reduced to 70%.
- Added tooltip when mouseovering a reference on how to pin the popup.
