### ISSUE TITLE
FR: Upload PDF file

### ISSUE THREAD

**Issue by dinogrgic1** [clippydsdone/clippy-frontend#36]

**Comment by nsm18002** [comment]
2022-11-08 - 1h30m
Attempted to fix URL problem for issue -36. Apparently for security reasons JavaScipt has no access to system file URLs (https://stackoverflow.com/questions/15201071/how-to-get-full-path-of-selected-file-on-change-of-input-type-file-using-jav)(https://stackoverflow.com/questions/61897410/how-to-get-path-directory-of-file-when-user-selected-in-input-type-file), Attempts to access file url yielded the path "C:\fakepath\document.pdf".

**Comment by nsm18002** [comment]
2022-11-08 - 2h
Looked into using localStorage and sessionStorage to store a cached version of the pdf, supposedly you can feed the pdf as a "Uint8Array" into the file url and pdf.js will load it.
However, the files are too large, and the browser throws an exception "Failed to execute 'setItem' on 'Storage': Setting the value of 'lastOpenedDocument' exceeded the quota."
